---
Name: khalsa-jio-alt-generator-config
---

Silverstripe\Assets\Image:
  extensions:
    - KhalsaJio\AltGenerator\Extension\ImageAltGeneratorExtension

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - KhalsaJio\AltGenerator\Extension\ImageAltGeneratorFormFactoryExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'khalsa-jio/silverstripe-alt-generator: client/dist/js/bundle.js'
