name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
      actions: write
    with:
      simple_matrix: true
      php_versions: '8.0, 8.1, 8.2'
      php_extensions: 'intl, mbstring, xml, zip'
      php_ini_overrides: |
        error_reporting = E_ALL
        display_errors = 1
        display_startup_errors = 1
        memory_limit = -1
      composer_args: '--prefer-dist --no-progress --no-suggest'